"""
Manages interactions with the ChromaDB vector store.

This module handles the creation of ChromaDB collections, addition of documents
(text chunks with metadata and embeddings), and querying of the vector store
with support for different embedding models and relevance score filtering.

Collection Naming Strategy:
Collections are named using a prefix (default: 'rag_documents') combined with a
sanitized version of the embedding model name (e.g., 'all-MiniLM-L6-v2' becomes
'all-MiniLM-L6-v2', while 'sentence-transformers/all-MiniLM-L6-v2' would become
'sentence-transformers_all-MiniLM-L6-v2'). This ensures that documents processed
with different embedding models are stored in separate collections.
"""
import chromadb
from chromadb.utils import embedding_functions
import os

# Define the path for persistent storage of ChromaDB.
# This path is relative to this file, creating 'vector_db' at the project root.
VECTOR_DB_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "vector_db")
os.makedirs(VECTOR_DB_PATH, exist_ok=True) # Ensure the directory exists

# Initialize a persistent ChromaDB client.
client = chromadb.PersistentClient(path=VECTOR_DB_PATH)

# Default sentence-transformer model for embeddings.
DEFAULT_EMBEDDING_MODEL = "all-MiniLM-L6-v2"

def get_collection(collection_name_prefix: str = "rag_documents", embedding_model_name: str = DEFAULT_EMBEDDING_MODEL):
    """
    Retrieves an existing ChromaDB collection or creates it if it doesn't exist.
    The collection is configured with a sentence-transformer model for embeddings.

    The actual collection name is dynamically generated by appending a sanitized
    version of the `embedding_model_name` to the `collection_name_prefix`.

    Args:
        collection_name_prefix: The base name for the collection.
        embedding_model_name: The name of the sentence-transformer model to use
                              (e.g., 'all-MiniLM-L6-v2').

    Returns:
        A chromadb.Collection object.
    """
    # Sanitize model name for use in collection names (e.g., replace '/' with '_').
    sanitized_model_name = embedding_model_name.replace("/", "_").replace(".", "_")
    effective_collection_name = f"{collection_name_prefix}_{sanitized_model_name}"

    # Initialize the embedding function with the specified sentence-transformer model.
    # Langchain's SentenceTransformerEmbeddingFunction is a wrapper around chromadb's.
    # For direct chromadb usage, this is the correct way.
    ef = embedding_functions.SentenceTransformerEmbeddingFunction(model_name=embedding_model_name)
    
    collection = client.get_or_create_collection(
        name=effective_collection_name,
        embedding_function=ef  # Assign the embedding function to the collection
    )
    return collection

def add_documents_to_store(
    text_chunks: list[str], 
    metadatas: list[dict] = None, 
    ids: list[str] = None,
    collection_name_prefix: str = "rag_documents",
    embedding_model_name: str = DEFAULT_EMBEDDING_MODEL
):
    """
    Adds text chunks, their metadatas, and IDs to the specified ChromaDB collection.
    Embeddings are generated automatically by the collection's embedding function.

    Args:
        text_chunks: A list of text strings (document chunks).
        metadatas: A list of metadata dictionaries, one for each text chunk.
        ids: A list of unique IDs, one for each text chunk. If None, IDs are auto-generated.
        collection_name_prefix: The prefix for the collection name.
        embedding_model_name: The embedding model to use for this batch of documents.
    
    Raises:
        ValueError: If the lengths of text_chunks, metadatas (if provided), and ids (if provided)
                    do not match.
    """
    collection = get_collection(collection_name_prefix, embedding_model_name)
    
    # Auto-generate IDs if not provided. These IDs include the collection name
    # to help ensure uniqueness if the same content is processed with different models.
    if not ids:
        ids = [f"chunk_{i}_{collection.name}" for i in range(len(text_chunks))] 
    
    # Create empty metadatas if not provided.
    if not metadatas:
        metadatas = [{} for _ in range(len(text_chunks))]
    
    # Store the original embedding model name in each item's metadata for clarity/tracking.
    for i in range(len(metadatas)):
        metadatas[i]['embedding_model'] = embedding_model_name

    if not (len(text_chunks) == len(metadatas) == len(ids)):
        raise ValueError("text_chunks, metadatas, and ids must have the same number of elements.")

    collection.add(
        documents=text_chunks,
        metadatas=metadatas,
        ids=ids
    )
    print(f"Added {len(text_chunks)} documents to collection '{collection.name}' using model '{embedding_model_name}'.")


def query_vector_store(
    query_text: str, 
    top_k: int = 5, 
    collection_name_prefix: str = "rag_documents",
    embedding_model_name: str = DEFAULT_EMBEDDING_MODEL,
    relevance_score_threshold: float = None 
) -> dict:
    """
    Queries the vector store for documents most similar to the query_text,
    optionally filtering results by a relevance score threshold (L2 distance).

    Args:
        query_text: The text to search for.
        top_k: The number of results to initially retrieve from the database.
        collection_name_prefix: Prefix for the collection name.
        embedding_model_name: The embedding model associated with the collection to query.
        relevance_score_threshold: Maximum L2 distance for a result to be considered relevant.
                                   ChromaDB uses L2 distance by default for SentenceTransformers;
                                   lower values indicate higher relevance (more similar).
                                   If None, no filtering based on distance is applied.

    Returns:
        A dictionary containing the query results, potentially filtered.
        Keys: 'ids', 'documents', 'metadatas', 'distances'.
    """
    collection = get_collection(collection_name_prefix, embedding_model_name)
    
    # Perform the query, ensuring distances are included for filtering.
    results = collection.query(
        query_texts=[query_text], # Must be a list of query texts
        n_results=top_k,
        include=['metadatas', 'documents', 'distances'] 
    )

    # Apply relevance score filtering if a threshold is provided.
    if relevance_score_threshold is not None and results.get('distances'):
        filtered_ids = []
        filtered_documents = []
        filtered_metadatas = []
        filtered_distances = []

        # ChromaDB query results are lists of lists (one inner list per query_text).
        # Since we query with a single text, we access the first element (index 0).
        original_ids = results.get('ids', [[]])[0]
        original_documents = results.get('documents', [[]])[0]
        original_metadatas = results.get('metadatas', [[]])[0]
        original_distances = results.get('distances', [[]])[0]

        for i in range(len(original_documents)):
            # L2 distance: lower is better (more similar).
            if original_distances[i] < relevance_score_threshold:
                # Chroma might not return IDs if they were not explicitly provided during `add`.
                # Or if the collection was empty and `add` was never called.
                if original_ids: 
                     filtered_ids.append(original_ids[i])
                filtered_documents.append(original_documents[i])
                filtered_metadatas.append(original_metadatas[i])
                filtered_distances.append(original_distances[i])
        
        # Replace original results with filtered lists, maintaining the expected structure.
        results['ids'] = [filtered_ids] # Structure is list of lists
        results['documents'] = [filtered_documents]
        results['metadatas'] = [filtered_metadatas]
        results['distances'] = [filtered_distances]
        
        print(f"Query: '{query_text}'. Initial results: {len(original_documents)}. Filtered results (threshold < {relevance_score_threshold}): {len(filtered_documents)}.")
    elif relevance_score_threshold is not None:
        # Handle case where threshold is set but distances are missing (should not happen with 'include' above)
        print(f"Warning: Relevance score threshold provided for query '{query_text}', but no distances found in results. No filtering applied.")

    return results

# Example Usage section for local testing and demonstration.
if __name__ == '__main__':
    print(f"ChromaDB persistent client initialized at: {VECTOR_DB_PATH}")

    # Ensure data exists for default model to test thresholding
    default_collection_for_test = get_collection(embedding_model_name=DEFAULT_EMBEDDING_MODEL)
    if default_collection_for_test.count() == 0:
        print(f"Populating collection '{default_collection_for_test.name}' for threshold test...")
        sample_chunks_for_test = [
            "The quick brown fox jumps over the lazy dog.", 
            "General information about vector databases and their importance in AI.", 
            "Exploring advanced AI concepts like neural networks and deep learning.",
            "Another document about vector databases, focusing on ChromaDB.",
            "A document discussing the theoretical aspects of vector embeddings."
        ]
        meta_for_test = [{"source": "test_doc.txt", "chunk_num": i} for i, _ in enumerate(sample_chunks_for_test)]
        add_documents_to_store(sample_chunks_for_test, meta_for_test, embedding_model_name=DEFAULT_EMBEDDING_MODEL)
        print(f"Collection '{default_collection_for_test.name}' now has {default_collection_for_test.count()} documents.")
    else:
        print(f"Collection '{default_collection_for_test.name}' already has {default_collection_for_test.count()} documents.")

    print(f"\n--- Testing with Relevance Score Threshold using model '{DEFAULT_EMBEDDING_MODEL}' ---")
    query = "information about vector databases"
    print(f"Querying for: '{query}'")

    results_no_filter = query_vector_store(query, top_k=5, embedding_model_name=DEFAULT_EMBEDDING_MODEL)
    print(f"\nResults (no filter, top_k=5):")
    if results_no_filter.get('documents') and results_no_filter['documents'][0]:
        for i, doc_text in enumerate(results_no_filter['documents'][0]):
            dist = results_no_filter['distances'][0][i] if results_no_filter.get('distances') and results_no_filter['distances'][0] else 'N/A'
            print(f"  Doc: {doc_text[:50]}..., Dist: {dist}")
    else:
        print("  No results or empty documents list.")

    # For L2 distance, smaller is better. Typical "good" L2 distances are often < 1.0.
    thresholds_to_test = [1.5, 1.0, 0.7, 0.5, 0.3] 
    for thold in thresholds_to_test:
        print(f"\nResults (threshold < {thold}, top_k=5):")
        results_filtered = query_vector_store(query, top_k=5, embedding_model_name=DEFAULT_EMBEDDING_MODEL, relevance_score_threshold=thold)
        if results_filtered.get('documents') and results_filtered['documents'][0]:
            for i, doc_text in enumerate(results_filtered['documents'][0]):
                dist = results_filtered['distances'][0][i] if results_filtered.get('distances') and results_filtered['distances'][0] else 'N/A'
                print(f"  Doc: {doc_text[:50]}..., Dist: {dist}")
        else:
            print(f"  No results passed the threshold {thold}.")
            
    # Test with a different model if populated
    other_model_example = "paraphrase-MiniLM-L3-v2" 
    other_collection_for_test = get_collection(embedding_model_name=other_model_example)
    if other_collection_for_test.count() > 0:
        print(f"\n--- Testing with Relevance Score Threshold using model '{other_model_example}' ---")
        query_other = "document content example" 
        results_other_filtered = query_vector_store(query_other, top_k=3, embedding_model_name=other_model_example, relevance_score_threshold=1.0)
        print(f"Results for '{other_model_example}' (threshold < 1.0):")
        if results_other_filtered.get('documents') and results_other_filtered['documents'][0]:
            for i, doc_text in enumerate(results_other_filtered['documents'][0]):
                dist = results_other_filtered['distances'][0][i] if results_other_filtered.get('distances') and results_other_filtered['distances'][0] else 'N/A'
                print(f"  Doc: {doc_text[:50]}..., Dist: {dist}")
        else:
            print("  No results or empty documents list for other model with this threshold.")
    else:
        print(f"\nCollection for model '{other_model_example}' is empty. Skipping threshold test for it.")

    print(f"\nList of all collections in DB: {[col.name for col in client.list_collections()]}")
